// Generates seed-test-data.sql for POS Restaurante
// Usage: node scripts/generate-seed.js > scripts/seed-test-data.sql

const PRODUCTS = [
  { id: 1,  name: "Bandeja Paisa",                cat: 1, price: 15000 },
  { id: 2,  name: "Bandeja de Pollo",             cat: 1, price: 12000 },
  { id: 3,  name: "Arepa de Choclo con Queso",    cat: 1, price: 8000 },
  { id: 4,  name: "Bandeja de Pescado",           cat: 1, price: 18000 },
  { id: 5,  name: "Gaseosa Personal",             cat: 2, price: 3000 },
  { id: 6,  name: "Gaseosa 1.5L",                 cat: 2, price: 5000 },
  { id: 7,  name: "Jugo Natural",                 cat: 2, price: 4500 },
  { id: 8,  name: "Cafe",                         cat: 2, price: 2000 },
  { id: 9,  name: "Postre Tres Leches",           cat: 3, price: 6000 },
  { id: 10, name: "Adicional de Arroz",           cat: 4, price: 2000 },
  { id: 11, name: "Adicional de Frijoles",        cat: 4, price: 2000 },
  { id: 12, name: "Adicional de Patacones",       cat: 4, price: 2500 },
];

const CLIENTS = [
  { id: 1, name: "Juan Perez",    phone: "3001234567",  addr: "Calle 1 #2-3" },
  { id: 2, name: "Maria Garcia",  phone: "3007654321",  addr: "Cra 4 #5-6" },
  { id: 3, name: "Carlos Lopez",  phone: "3105551212",  addr: "Av 7 #8-9" },
  { id: 4, name: "Ana Martinez",  phone: "3206663434",  addr: "Calle 10 #11-12" },
];

function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }

// Generate 1-3 line items for a venta
function generateItems(targetTotal) {
  const items = [];
  let remaining = targetTotal;
  const count = 2 + Math.floor(Math.random() * 2); // 2-3 items
  const used = new Set();
  
  for (let i = 0; i < count; i++) {
    const isLast = i === count - 1;
    const affordable = PRODUCTS.filter(p => p.price <= remaining + 1000 && !used.has(p.id));
    if (affordable.length === 0) break;
    const product = affordable.sort((a, b) => (b.cat === 1 ? 1 : 0) - (a.cat === 1 ? 1 : 0))[0];
    
    used.add(product.id);
    let qty = 1;
    if (isLast && remaining > product.price * 2) {
      qty = Math.floor(remaining / product.price);
    } else if (product.cat !== 1 && remaining > product.price * 2) {
      qty = 1 + Math.floor(Math.random() * 2);
    }
    const subtotal = product.price * qty;
    if (subtotal > remaining + 2000) continue;
    items.push({ productId: product.id, qty, price: product.price, subtotal });
    remaining -= subtotal;
  }
  
  const total = items.reduce((s, i) => s + i.subtotal, 0);
  return { items: items.length > 0 ? items : [{ productId: 1, qty: 1, price: 15000, subtotal: 15000 }], total };
}

function toDateStr(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

const MARCH_DATES = [2, 4, 6, 10, 13, 17, 20, 31];
const APRIL_DATES = [1, 3, 7, 10, 17, 21, 24, 28];
const MAY_CLOSED_DATES = [5, 8, 15, 22];

let turnId = 0;
let ventaId = 0;
let gastoId = 0;
let abonoId = 0;
let movId = 0;

const lines = [];
function L(s) { lines.push(s); }

// Build all turns
function buildTurns() {
  L("-- ============================================================");
  L("-- SEED TEST DATA for POS Restaurante");
  L("-- Auto-generated by generate-seed.js");
  L("-- Prerequisite: App must have started once (bootstrap creates");
  L("--   Roles: ADMIN=1, CAJA=2, DOMI=3");
  L("--   Categorias: Almuerzos=1, Bebidas=2, Postres=3, Adicionales=4");
  L("--   TiposGasto: Alimentos=1..Impuestos=11");
  L("--   Admin user: admin1 / admin1 (id=1)");
  L("-- ============================================================");
  L("");
  L("-- Clean existing test data (order respects FK constraints)");
  L("DELETE FROM movimientos_financieros;");
  L("DELETE FROM audit_changes;");
  L("DELETE FROM audit_events;");
  L("DELETE FROM abonos_fiado;");
  L("DELETE FROM venta_pago_detalle;");
  L("DELETE FROM venta_detalles;");
  L("DELETE FROM ventas;");
  L("DELETE FROM gastos_caja;");
  L("DELETE FROM gastos_admin;");
  L("DELETE FROM inventarios_diarios;");
  L("DELETE FROM menus_diarios;");
  L("DELETE FROM turnos_caja;");
  L("DELETE FROM clientes;");
  L("DELETE FROM productos;");
  L("DELETE FROM usuarios WHERE username NOT IN ('admin1');");
  L("");
  
  // Users
  L("-- ============================================================");
  L("-- USERS (password for cajero1/cajero2: password123)");
  L("-- ============================================================");
  L("INSERT INTO usuarios (id, username, password, rol_id, activo) VALUES");
  L("(2, 'cajero1', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 2, 1),");
  L("(3, 'cajero2', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 2, 1);");
  L("");
  
  // Clients
  L("-- ============================================================");
  L("-- CLIENTS");
  L("-- ============================================================");
  L("INSERT INTO clientes (id, nombre, telefono, direccion_predeterminada, notas, activo, fecha_creacion, fecha_actualizacion) VALUES");
  for (const c of CLIENTS) {
    L(`(${c.id}, '${c.name}', '${c.phone}', '${c.addr}', NULL, 1, '2026-01-01 00:00:00', '2026-01-01 00:00:00'),`);
  }
  replaceLast(";");
  L("");
  
  // Products
  L("-- ============================================================");
  L("-- PRODUCTS");
  L("-- ============================================================");
  L("INSERT INTO productos (id, nombre, descripcion, precio, categoria_id, activo, tipo_venta) VALUES");
  for (const p of PRODUCTS) {
    const desc = p.cat === 1 ? `'${p.name} tradicional'` : "NULL";
    const tipoVenta = p.cat === 1 ? "MENU_DIARIO" : "SIEMPRE_DISPONIBLE";
    L(`(${p.id}, '${p.name}', ${desc}, ${p.price}.00, ${p.cat}, 1, '${tipoVenta}'),`);
  }
  replaceLast(";");
  
  // Generate turns
  L("");
  L("-- ============================================================");
  L("-- TURNOS CAJA");
  L("-- ============================================================");
  
  const allTurns = [];
  
  function addTurn(dateStr, isClosed) {
    turnId++;
    const estado = isClosed ? "CERRADO" : "ABIERTO";
    const horaCierre = isClosed ? "'" + dateStr + " 16:30:00'" : "NULL";
    const montoInicial = 200000;
    
    // Generate 4 ventas per turn
    const ventas = [];
    for (let i = 0; i < 4; i++) {
      ventaId++;
      const hour = 9 + i * 2;
      const min = 15 + i * 17;
      const fecha = `${dateStr} ${String(hour).padStart(2, "0")}:${String(min % 60).padStart(2, "0")}:00`;
      
      let formaPago, condicionPago, isFiado = false, clienteId = "NULL", total;
      
      if (i < 2) {
        formaPago = "EFECTIVO";
        condicionPago = "CONTADO";
        total = 50000 + Math.floor(Math.random() * 40000);
      } else if (i === 2) {
        formaPago = "TRANSFERENCIA";
        condicionPago = "CONTADO";
        total = 60000 + Math.floor(Math.random() * 50000);
      } else {
        formaPago = "FIADO";
        condicionPago = "FIADO";
        isFiado = true;
        const client = CLIENTS[(turnId - 1) % CLIENTS.length];
        clienteId = String(client.id);
        total = 40000 + Math.floor(Math.random() * 40000);
      }
      
      const tipoVenta = i === 2 ? "DOMICILIO" : "LOCAL";
      const { items } = generateItems(total);
      const actualTotal = items.reduce((s, it) => s + it.subtotal, 0);
      const saldoPendiente = isFiado ? actualTotal : 0;
      
      ventas.push({ id: ventaId, fecha, tipo: tipoVenta, formaPago, condicionPago, total: actualTotal, saldoPendiente, clienteId, items, isFiado });
    }
    
    const totalVentas = ventas.reduce((s, v) => s + v.total, 0);
    const totalGastos = isClosed ? 50000 : 0;
    const montoFinal = montoInicial + totalVentas - totalGastos;
    const efectivoContado = ventas.filter(v => v.formaPago === "EFECTIVO").reduce((s, v) => s + v.total, 0);
    const transContado = ventas.filter(v => v.formaPago === "TRANSFERENCIA").reduce((s, v) => s + v.total, 0);
    
    allTurns.push({ id: turnId, ventas, date: dateStr, isClosed, totalVentas, totalGastos, montoFinal, efectivoContado, transContado });
  }
  
  // March turns
  for (const day of MARCH_DATES) addTurn(`2026-03-${String(day).padStart(2, "0")}`, true);
  // April turns
  for (const day of APRIL_DATES) addTurn(`2026-04-${String(day).padStart(2, "0")}`, true);
  // May closed turns
  for (const day of MAY_CLOSED_DATES) addTurn(`2026-05-${String(day).padStart(2, "0")}`, true);
  // May open turn
  addTurn("2026-05-26", false);
  
  // Write turn insert
  L("INSERT INTO turnos_caja (id, version, fecha_apertura, fecha_cierre, monto_inicial, monto_final, total_ventas, total_gastos, esperado, faltante, efectivo_contado, transferencias_verificadas, diferencia_efectivo, diferencia_transferencias, total_verificado, diferencia_total, estado, usuario_id) VALUES");
  for (const t of allTurns) {
    const mf = t.isClosed ? t.montoFinal.toFixed(2) : "NULL";
    const ec = t.isClosed ? t.efectivoContado.toFixed(2) : "NULL";
    const tc = t.isClosed ? t.transContado.toFixed(2) : "NULL";
    const horaCierre = t.isClosed ? `'${t.date} 16:30:00'` : "NULL";
    L(`(${t.id}, 0, '${t.date} 08:00:00', ${horaCierre}, 200000.00, ${mf}, ${t.totalVentas.toFixed(2)}, ${t.totalGastos.toFixed(2)}, ${mf}, ${t.isClosed ? "0.00" : "NULL"}, ${ec}, ${tc}, ${t.isClosed ? "0.00" : "NULL"}, ${t.isClosed ? "0.00" : "NULL"}, ${mf}, ${t.isClosed ? "0.00" : "NULL"}, '${t.isClosed ? "CERRADO" : "ABIERTO"}', 2),`);
  }
  replaceLast(";");
  
  // VENTAS
  L("");
  L("-- ============================================================");
  L("-- VENTAS, VENTA_DETALLES, VENTA_PAGO_DETALLE");
  L("-- ============================================================");
  
  for (const turn of allTurns) {
    L(`-- Turn ${turn.id} (${turn.date})${turn.isClosed ? "" : " -- OPEN turn"}`);
    L("INSERT INTO ventas (id, version, fecha, tipo_venta, estado, forma_pago, condicion_pago, total, saldo_pendiente, cliente_id, usuario_id, turno_id, para_llevar) VALUES");
    for (const v of turn.ventas) {
      const paraLlevar = v.tipo === "DOMICILIO" ? 1 : 0;
      L(`(${v.id}, 0, '${v.fecha}', '${v.tipo}', 'DESPACHADA', '${v.formaPago}', '${v.condicionPago}', ${v.total.toFixed(2)}, ${v.saldoPendiente.toFixed(2)}, ${v.clienteId}, 2, ${turn.id}, ${paraLlevar}),`);
    }
    replaceLast(";");
    
    // VENTA_DETALLES
    L("INSERT INTO venta_detalles (venta_id, producto_id, cantidad, precio_unitario, subtotal) VALUES");
    for (const v of turn.ventas) {
      for (const item of v.items) {
        L(`(${v.id}, ${item.productId}, ${item.qty}, ${item.price}.00, ${item.subtotal}.00),`);
      }
    }
    replaceLast(";");
    
    // VENTA_PAGO_DETALLE (only for non-fiado ventas)
    const contadoVentas = turn.ventas.filter(v => !v.isFiado);
    if (contadoVentas.length > 0) {
      L("INSERT INTO venta_pago_detalle (venta_id, pago_efectivo, pago_transferencia, recibido_efectivo, recibido_transferencia, cambio_efectivo, updated_at) VALUES");
      for (const v of contadoVentas) {
        if (v.formaPago === "EFECTIVO") {
          const recibido = v.total + Math.ceil(Math.random() * 10000 / 1000) * 1000;
          const cambio = recibido - v.total;
          L(`(${v.id}, ${v.total.toFixed(2)}, 0.00, ${recibido.toFixed(2)}, 0.00, ${cambio.toFixed(2)}, '${v.fecha}'),`);
        } else {
          L(`(${v.id}, 0.00, ${v.total.toFixed(2)}, 0.00, ${v.total.toFixed(2)}, 0.00, '${v.fecha}'),`);
        }
      }
      replaceLast(";");
    }
  }
  
  // GASTOS_CAJA
  L("");
  L("-- ============================================================");
  L("-- GASTOS_CAJA (one per closed turn)");
  L("-- ============================================================");
  const closedTurns = allTurns.filter(t => t.isClosed);
  L("INSERT INTO gastos_caja (id, descripcion, monto, monto_efectivo, monto_transferencia, fecha, tipo_gasto_id, turno_id, usuario_id) VALUES");
  for (const turn of closedTurns) {
    gastoId++;
    L(`(${gastoId}, 'Pago nomina chef', 50000.00, 30000.00, 20000.00, '${turn.date} 15:00:00', 4, ${turn.id}, 2),`);
  }
  replaceLast(";");
  
  // GASTOS_ADMIN
  L("");
  L("-- ============================================================");
  L("-- GASTOS_ADMIN (one per month)");
  L("-- ============================================================");
  L("INSERT INTO gastos_admin (id, fecha, descripcion, monto, monto_efectivo, monto_transferencia, tipo_gasto_id, usuario_id) VALUES");
  L("(1, '2026-03-15', 'Pago arriendo local', 800000.00, 800000.00, 0.00, 6, 1),");
  L("(2, '2026-04-15', 'Pago arriendo local', 800000.00, 800000.00, 0.00, 6, 1),");
  L("(3, '2026-05-15', 'Pago arriendo local', 800000.00, 800000.00, 0.00, 6, 1);");
  
  // ABONOS_FIADO
  L("");
  L("-- ============================================================");
  L("-- ABONOS_FIADO");
  L("-- ============================================================");
  const abonoData = [
    { fecha: "2026-03-10", monto: 55000, montoEf: 30000, montoTrans: 25000, fp: "EFECTIVO", cliente: 1, turno: 4 },
    { fecha: "2026-03-20", monto: 60000, montoEf: 60000, montoTrans: 0, fp: "EFECTIVO", cliente: 2, turno: 7 },
    { fecha: "2026-04-05", monto: 70000, montoEf: 40000, montoTrans: 30000, fp: "EFECTIVO", cliente: 3, turno: 10 },
    { fecha: "2026-04-18", monto: 50000, montoEf: 0, montoTrans: 50000, fp: "TRANSFERENCIA", cliente: 1, turno: 13 },
    { fecha: "2026-05-10", monto: 65000, montoEf: 35000, montoTrans: 30000, fp: "EFECTIVO", cliente: 2, turno: 18 },
    { fecha: "2026-05-20", monto: 45000, montoEf: 45000, montoTrans: 0, fp: "EFECTIVO", cliente: 4, turno: 20 },
  ];
  
  L("INSERT INTO abonos_fiado (id, fecha, monto, monto_efectivo, monto_transferencia, forma_pago, observacion, cliente_id, usuario_id, turno_id) VALUES");
  for (let i = 0; i < abonoData.length; i++) {
    const ab = abonoData[i];
    L(`(${i + 1}, '${ab.fecha} 12:00:00', ${ab.monto}.00, ${ab.montoEf}.00, ${ab.montoTrans}.00, '${ab.fp}', NULL, ${ab.cliente}, 2, ${ab.turno}),`);
  }
  replaceLast(";");
  
  // MOVIMIENTOS_FINANCIEROS
  L("");
  L("-- ============================================================");
  L("-- MOVIMIENTOS_FINANCIEROS");
  L("-- ============================================================");
  L("INSERT INTO movimientos_financieros (id, fecha, tipo, medio, monto, direccion, turno_id, venta_id, abono_fiado_id, gasto_caja_id, gasto_admin_id, usuario_id, descripcion) VALUES");
  
  for (const turn of allTurns) {
    for (const v of turn.ventas) {
      if (v.formaPago === "EFECTIVO") {
        movId++;
        L(`(${movId}, '${v.fecha}', 'VENTA_CONTADO', 'EFECTIVO', ${v.total.toFixed(2)}, 1, ${turn.id}, ${v.id}, NULL, NULL, NULL, 2, NULL),`);
      } else if (v.formaPago === "TRANSFERENCIA") {
        movId++;
        L(`(${movId}, '${v.fecha}', 'VENTA_CONTADO', 'TRANSFERENCIA', ${v.total.toFixed(2)}, 1, ${turn.id}, ${v.id}, NULL, NULL, NULL, 2, NULL),`);
      } else if (v.formaPago === "FIADO") {
        movId++;
        L(`(${movId}, '${v.fecha}', 'VENTA_FIADA', 'CARTERA', ${v.total.toFixed(2)}, 1, ${turn.id}, ${v.id}, NULL, NULL, NULL, 2, NULL),`);
      }
    }
    
    // Gasto caja movements
    if (turn.isClosed) {
      // EFECTIVO portion
      movId++;
      L(`(${movId}, '${turn.date} 15:00:00', 'GASTO_CAJA', 'EFECTIVO', 30000.00, -1, ${turn.id}, NULL, NULL, ${turn.id}, NULL, 2, NULL),`);
      // TRANSFERENCIA portion
      movId++;
      L(`(${movId}, '${turn.date} 15:00:00', 'GASTO_CAJA', 'TRANSFERENCIA', 20000.00, -1, ${turn.id}, NULL, NULL, ${turn.id}, NULL, 2, NULL),`);
    }
  }
  
  // Abono movements
  for (let i = 0; i < abonoData.length; i++) {
    const ab = abonoData[i];
    if (ab.montoEf > 0) {
      movId++;
      L(`(${movId}, '${ab.fecha} 12:00:00', 'ABONO_FIADO', 'EFECTIVO', ${ab.montoEf}.00, 1, ${ab.turno}, NULL, ${i + 1}, NULL, NULL, 2, NULL),`);
    }
    if (ab.montoTrans > 0) {
      movId++;
      L(`(${movId}, '${ab.fecha} 12:00:00', 'ABONO_FIADO', 'TRANSFERENCIA', ${ab.montoTrans}.00, 1, ${ab.turno}, NULL, ${i + 1}, NULL, NULL, 2, NULL),`);
    }
  }
  
  // Gasto admin movements
  for (let i = 1; i <= 3; i++) {
    const month = ["2026-03-15", "2026-04-15", "2026-05-15"][i - 1];
    movId++;
    L(`(${movId}, '${month} 10:00:00', 'GASTO_ADMIN', 'EFECTIVO', 800000.00, -1, NULL, NULL, NULL, NULL, ${i}, 1, NULL),`);
  }
  
  replaceLast(";");
  
  L("");
  L("-- ============================================================");
  L("-- END SEED DATA");
  L("-- ============================================================");
}

function replaceLast(suffix) {
  const last = lines.pop();
  lines.push(last.replace(/,$/, suffix));
}

buildTurns();

process.stdout.write(lines.join("\n"));
